version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server

  # Melodayz Server service
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - '4000:4000'
