# Exported from Render on 2025-08-02T12:58:59Z
services:
- type: web
  name: melodayzmusic-api
  runtime: docker
  repo: https://github.com/bossnare/melodayzmusic
  plan: free
  envVars:
  - key: DB_NAME
    sync: false
  - key: MONGO_URI
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
  rootDir: apps/server
version: "1"
